### ISSUE TITLE
关于删除app的操作

### ISSUE THREAD

**Issue by Hemione521** [liu-xinhui/appPublishFront#1]
您好，这个有打算做删除的操作嘛？我看目前是暂时不支持删除上传的app的操作的。

**Comment by jk030611** [comment]
本地编译报错了
npm ERR! code 1
npm ERR! path D:\web\appPublishFront-github\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\nodejs\node.exe D:\web\appPublishFront-github\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\web\\appPublishFront-github\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.14.2 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\web\appPublishFront-github\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\web\appPublishFront-github\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\web\appPublishFront-github\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\web\appPublishFront-github\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\web\appPublishFront-github\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\web\appPublishFront-github\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\web\appPublishFront-github\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\web\appPublishFront-github\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\web\appPublishFront-github\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\web\appPublishFront-github\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\web\appPublishFront-github\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\web\appPublishFront-github\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python D:\Python\Python311\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: D:\Python\Python311\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "D:\\nodejs\\node.exe" "D:\\web\\appPublishFront-github\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\web\appPublishFront-github\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.14.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-28T09_09_33_933Z-debug-0.log

**Comment by Hemione521** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
